Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1255','09','df','1','oui','dsdd','in','oui');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1251','09','dd','0','dff','de','de','non');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1275','09','df','1','oui','dsdd','in','oui');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1245','06','dd','0','dff','de','de','non');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1215','09','dd','0','dff','de','de','non');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1205','01','df','1','oui','dsdd','in','oui');
Insert into MODEL_CLIENT (ID_CLIENT,CRM_ROLE,CUST_INCOME,HEDG_STATUS,LEGAL_CODE,PERS_CLASS,BUS_LINE,STATUS_CODE) values ('1254','09','dd','0','dff','de','de','non');